name: aipsych
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - pip:
      - torch
      - transformers
      - shap
      - lime
      - networkx
      - mesa
      - nltk
      - textblob
      - jupyter-book
      - pyarrow
      - xgboost
      - nbval
      - nbconvert
